/*
  M-MKULIMA NYANDARUA DATABASE MIGRATION SCRIPT (BULLETPROOF & IDEMPOTENT)
  Run this script in Supabase SQL Editor
*/

-- 1. FARMERS / ACCOUNTS TABLE
CREATE TABLE IF NOT EXISTS public.farmers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    ward TEXT NOT NULL DEFAULT 'Karau',
    farmer_id TEXT UNIQUE,
    is_admin BOOLEAN DEFAULT FALSE,
    role TEXT DEFAULT 'farmer',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. FODDER FEED LISTINGS TABLE
CREATE TABLE IF NOT EXISTS public.fodder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_sw TEXT,
    category TEXT NOT NULL DEFAULT 'Protein',
    category_sw TEXT,
    price TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    seller TEXT NOT NULL,
    phone TEXT NOT NULL,
    description TEXT,
    desc_sw TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. MARKETPLACE ITEMS TABLE (Livestock, Machinery, Produce)
CREATE TABLE IF NOT EXISTS public.marketplace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_sw TEXT,
    category TEXT NOT NULL DEFAULT 'Livestock',
    category_sw TEXT,
    price TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Ol Kalou',
    contact TEXT NOT NULL,
    description TEXT,
    desc_sw TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. VERIFIED VETERINARY OFFICERS TABLE
CREATE TABLE IF NOT EXISTS public.vets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    reg_number TEXT NOT NULL UNIQUE,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    phone TEXT NOT NULL,
    specialization TEXT NOT NULL,
    spec_sw TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. AGRICULTURAL SERVICES HUB TABLE
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_sw TEXT,
    category TEXT NOT NULL DEFAULT 'Silage',
    category_sw TEXT,
    rate TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    provider TEXT NOT NULL,
    phone TEXT NOT NULL,
    description TEXT,
    desc_sw TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. AGRI-CHEMICALS & CONCENTRATES HUB TABLE
CREATE TABLE IF NOT EXISTS public.chemicals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Concentrate',
    price TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    contact TEXT NOT NULL,
    description TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ORDERS & DELIVERY TRACKING TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    items_summary TEXT NOT NULL,
    total_amount TEXT NOT NULL,
    buyer_name TEXT NOT NULL,
    buyer_phone TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    ward TEXT NOT NULL DEFAULT 'Karau',
    status TEXT DEFAULT 'Order Submitted - Pending Call Back',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. PENDING APPROVALS QUEUE TABLE (Backend Moderation)
CREATE TABLE IF NOT EXISTS public.pending_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    category TEXT,
    price TEXT,
    subcounty TEXT,
    seller TEXT,
    phone TEXT,
    description TEXT,
    image TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. EMERGENCY VET DISPATCH REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.vet_emergencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    ward TEXT NOT NULL DEFAULT 'Karau',
    emergency_type TEXT NOT NULL,
    status TEXT DEFAULT 'dispatched',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. M-PESA TRANSACTIONS LOG TABLE
CREATE TABLE IF NOT EXISTS public.mpesa_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_request_id TEXT UNIQUE,
    merchant_request_id TEXT,
    phone TEXT NOT NULL,
    amount NUMERIC,
    mpesa_receipt_number TEXT,
    result_code INT,
    result_desc TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ENABLE ROW LEVEL SECURITY ON ALL TABLES
ALTER TABLE public.farmers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fodder ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chemicals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vet_emergencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mpesa_transactions ENABLE ROW LEVEL SECURITY;

-- SAFE POLICY CREATION BLOCK (CHECK PG_POLICIES BEFORE CREATING TO PREVENT DUPLICATE ERROR 42710)
DO $$ 
BEGIN
    -- Farmers Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'farmers' AND policyname = 'Allow public read access on farmers') THEN
        CREATE POLICY "Allow public read access on farmers" ON public.farmers FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'farmers' AND policyname = 'Allow public insert access on farmers') THEN
        CREATE POLICY "Allow public insert access on farmers" ON public.farmers FOR INSERT WITH CHECK (true);
    END IF;

    -- Fodder Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'fodder' AND policyname = 'Allow public read access on fodder') THEN
        CREATE POLICY "Allow public read access on fodder" ON public.fodder FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'fodder' AND policyname = 'Allow public insert access on fodder') THEN
        CREATE POLICY "Allow public insert access on fodder" ON public.fodder FOR INSERT WITH CHECK (true);
    END IF;

    -- Marketplace Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'marketplace' AND policyname = 'Allow public read access on marketplace') THEN
        CREATE POLICY "Allow public read access on marketplace" ON public.marketplace FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'marketplace' AND policyname = 'Allow public insert access on marketplace') THEN
        CREATE POLICY "Allow public insert access on marketplace" ON public.marketplace FOR INSERT WITH CHECK (true);
    END IF;

    -- Vets Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'vets' AND policyname = 'Allow public read access on vets') THEN
        CREATE POLICY "Allow public read access on vets" ON public.vets FOR SELECT USING (true);
    END IF;

    -- Services Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'services' AND policyname = 'Allow public read access on services') THEN
        CREATE POLICY "Allow public read access on services" ON public.services FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'services' AND policyname = 'Allow public insert access on services') THEN
        CREATE POLICY "Allow public insert access on services" ON public.services FOR INSERT WITH CHECK (true);
    END IF;

    -- Chemicals Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chemicals' AND policyname = 'Allow public read access on chemicals') THEN
        CREATE POLICY "Allow public read access on chemicals" ON public.chemicals FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chemicals' AND policyname = 'Allow public insert access on chemicals') THEN
        CREATE POLICY "Allow public insert access on chemicals" ON public.chemicals FOR INSERT WITH CHECK (true);
    END IF;

    -- Orders Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'orders' AND policyname = 'Allow public read access on orders') THEN
        CREATE POLICY "Allow public read access on orders" ON public.orders FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'orders' AND policyname = 'Allow public insert access on orders') THEN
        CREATE POLICY "Allow public insert access on orders" ON public.orders FOR INSERT WITH CHECK (true);
    END IF;

    -- Pending Approvals Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'pending_approvals' AND policyname = 'Allow public read access on pending_approvals') THEN
        CREATE POLICY "Allow public read access on pending_approvals" ON public.pending_approvals FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'pending_approvals' AND policyname = 'Allow public insert access on pending_approvals') THEN
        CREATE POLICY "Allow public insert access on pending_approvals" ON public.pending_approvals FOR INSERT WITH CHECK (true);
    END IF;

    -- Vet Emergencies Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'vet_emergencies' AND policyname = 'Allow public read access on vet_emergencies') THEN
        CREATE POLICY "Allow public read access on vet_emergencies" ON public.vet_emergencies FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'vet_emergencies' AND policyname = 'Allow public insert access on vet_emergencies') THEN
        CREATE POLICY "Allow public insert access on vet_emergencies" ON public.vet_emergencies FOR INSERT WITH CHECK (true);
    END IF;

    -- Mpesa Transactions Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mpesa_transactions' AND policyname = 'Allow public read access on mpesa_transactions') THEN
        CREATE POLICY "Allow public read access on mpesa_transactions" ON public.mpesa_transactions FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mpesa_transactions' AND policyname = 'Allow public insert access on mpesa_transactions') THEN
        CREATE POLICY "Allow public insert access on mpesa_transactions" ON public.mpesa_transactions FOR INSERT WITH CHECK (true);
    END IF;
END $$;
