/*
  M-MKULIMA NYANDARUA DATABASE MIGRATION SCRIPT
  Run this script in Supabase SQL Editor
*/

CREATE TABLE IF NOT EXISTS public.farmers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    ward TEXT NOT NULL DEFAULT 'Karau',
    farmer_id TEXT UNIQUE,
    is_admin BOOLEAN DEFAULT FALSE,
    role TEXT DEFAULT 'farmer',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fodder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_sw TEXT,
    category TEXT NOT NULL DEFAULT 'Protein',
    category_sw TEXT,
    price TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    seller TEXT NOT NULL,
    phone TEXT NOT NULL,
    description TEXT,
    desc_sw TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.marketplace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_sw TEXT,
    category TEXT NOT NULL DEFAULT 'Livestock',
    category_sw TEXT,
    price TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT 'Ol Kalou',
    contact TEXT NOT NULL,
    description TEXT,
    desc_sw TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.vets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    reg_number TEXT NOT NULL UNIQUE,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    phone TEXT NOT NULL,
    specialization TEXT NOT NULL,
    spec_sw TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_sw TEXT,
    category TEXT NOT NULL DEFAULT 'Silage',
    category_sw TEXT,
    rate TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    provider TEXT NOT NULL,
    phone TEXT NOT NULL,
    description TEXT,
    desc_sw TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chemicals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Concentrate',
    price TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    contact TEXT NOT NULL,
    description TEXT,
    image TEXT,
    status TEXT DEFAULT 'approved',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    items_summary TEXT NOT NULL,
    total_amount TEXT NOT NULL,
    buyer_name TEXT NOT NULL,
    buyer_phone TEXT NOT NULL,
    subcounty TEXT NOT NULL DEFAULT 'Ol Kalou',
    ward TEXT NOT NULL DEFAULT 'Karau',
    status TEXT DEFAULT 'Order Submitted - Pending Call Back',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.pending_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    category TEXT,
    price TEXT,
    subcounty TEXT,
    seller TEXT,
    phone TEXT,
    description TEXT,
    image TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.farmers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fodder ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chemicals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_approvals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on farmers" ON public.farmers FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on farmers" ON public.farmers FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on fodder" ON public.fodder FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on fodder" ON public.fodder FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on marketplace" ON public.marketplace FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on marketplace" ON public.marketplace FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on vets" ON public.vets FOR SELECT USING (true);

CREATE POLICY "Allow public read access on services" ON public.services FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on services" ON public.services FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on chemicals" ON public.chemicals FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on chemicals" ON public.chemicals FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on orders" ON public.orders FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on pending_approvals" ON public.pending_approvals FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on pending_approvals" ON public.pending_approvals FOR INSERT WITH CHECK (true);
